# Generated by Django 4.2.3 on 2023-07-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknEat', '0004_cart_data_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_data',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
